#
# Copyright (C) 2009  Red Hat, Inc.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require 'rake'
require 'rake/testtask'

desc "Run basic unit tests"
Rake::TestTask.new("test") { |t|
  t.test_files = FileList[
    'tests/flavors_test.rb',
    'tests/realms_test.rb',
    'tests/images_test.rb',
    'tests/instances_test.rb',
    'tests/storage_volumes_test.rb',
    'tests/storage_snapshots_test.rb',
  ]
  t.verbose = false
  t.warning = false
}
