source "http://rubygems.org"

gemspec

platforms :jruby do
  gem 'jruby-openssl'
end

group :development do
  gem "rack-test"
  gem "minitest"
  gem "simplecov"
  gem "webmock"
  gem "vcr"
  gem "aws"
end

